### ISSUE TITLE
Missing data in the paper

### ISSUE THREAD

**Issue by HenryVVan** [cocoanlab/cocoanCORE#1]
Dear Professor

I hope this message finds you well. I am currently working on replicating your paper [An fMRI-Based Neurologic Signature of Physical Pain](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3691100/) and I encountered an issue while trying to access the data through the provided link in your original paper. Unfortunately, the link appears to be inaccessible or broken.

In the original text, you mentioned the following:

_In forced-choice discrimination, two activation maps from the same participant were compared, and the image with the higher overall signature response (i.e., the stronger expression of the signature pattern) was classified as associated with more pain. Forced-choice tests are particularly suitable for fMRI because they do not compare the signature response with a threshold that is fixed across persons. Therefore, they do not require people to use the pain-reporting scale in the same way, and they do not require the scale of fMRI activity to be the same across scanners (see the [Supplementary Appendix](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3691100/#SD1)). Sensitivity, specificity, positive predictive value, and decision accuracy are all equivalent in the forced-choice test. **The MATLAB code for implementing all analyses is available at http://wagerlab.colorado.edu/**._

I have reviewed the code and data in your GitHub repository, but I couldn't locate the data circled in red in the attached image. I apologize for any inconvenience.

<img width="512" alt="1694447948448" src="https://github.com/cocoanlab/cocoanCORE/assets/129581602/193bd07e-c20c-4ce1-88d6-873316ef6195">

Would it be possible for you to kindly provide me with an updated or alternative download link for the data? Your assistance in this matter would be greatly appreciated.

Thank you for your time and consideration.

**Comment by wanirepo** [comment]
Dear Henry, 

To obtain the NPS mask, please contact Professor Wager at tor.d.wager@dartmouth.edu and request a Material Transfer Agreement (MTA) form.

see https://sites.google.com/dartmouth.edu/canlab-brainpatterns/multivariate-brain-signatures/2013-nps

Best,
Wani

**Comment by HenryVVan** [comment]
Dear Professor

I'm grateful for the information you provided.

Wishing you all the best,
Henry
